{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "8825bce6-8f37-4f79-84ee-ea57e66e1d98",
   "metadata": {},
   "source": [
    "### Create the data preparation pipeline yaml"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "571d5d97-56df-4ab7-8eb6-dc3821fbcb07",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "\n",
    "# Define the path to the desired Python executable\n",
    "python_executable = os.path.expanduser('~/object-detection-project/env/bin/python')\n",
    "\n",
    "# The command you want to run\n",
    "comando_python = f\"{python_executable} pipeline/pipeline_with_pvc.py\"\n",
    "\n",
    "# Execute the command in the notebook cell\n",
    "!{comando_python}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "c95659f4-1d3f-4189-b576-f971e513c2a9",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "\n",
    "# Define the path to the desired Python executable\n",
    "python_executable = os.path.expanduser('~/object-detection-project/env/bin/python')\n",
    "\n",
    "# The command you want to run\n",
    "comando_python = f\"{python_executable} data_prep_pipeline.py\"\n",
    "\n",
    "# Execute the command in the notebook cell\n",
    "!{comando_python}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "09a6f3e3-e0cd-4c96-a8e8-6bd1cbba0ea0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/home/jovyan/object-detection-project/env/lib/python3.11/site-packages/kfp/dsl/component_decorator.py:126: FutureWarning: The default base_image used by the @dsl.component decorator will switch from 'python:3.9' to 'python:3.10' on Oct 1, 2025. To ensure your existing components work with versions of the KFP SDK released after that date, you should provide an explicit base_image argument and ensure your component works as intended on Python 3.10.\n",
      "  return component_factory.create_component_from_func(\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "\n",
    "# Define the path to the desired Python executable\n",
    "python_executable = os.path.expanduser('~/object-detection-project/env/bin/python')\n",
    "\n",
    "# The command you want to run\n",
    "comando_python = f\"{python_executable} ./pipeline_test/ask-resources-example.py\"\n",
    "\n",
    "# Execute the command in the notebook cell\n",
    "!{comando_python}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "b8bc571a-99e2-4eae-a61f-e3cdc019066e",
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    }
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/opt/conda/lib/python3.11/site-packages/kfp/client/client.py:159: FutureWarning: This client only works with Kubeflow Pipeline v2.0.0-beta.2 and later versions.\n",
      "  warnings.warn(\n",
      "ERROR:root:Failed to get healthz info attempt 1 of 5.\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp/client/client.py\", line 424, in get_kfp_healthz\n",
      "    return self._healthz_api.healthz_service_get_healthz()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api/healthz_service_api.py\", line 63, in healthz_service_get_healthz\n",
      "    return self.healthz_service_get_healthz_with_http_info(**kwargs)  # noqa: E501\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api/healthz_service_api.py\", line 134, in healthz_service_get_healthz_with_http_info\n",
      "    return self.api_client.call_api(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py\", line 364, in call_api\n",
      "    return self.__call_api(resource_path, method,\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py\", line 188, in __call_api\n",
      "    raise e\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py\", line 181, in __call_api\n",
      "    response_data = self.request(\n",
      "                    ^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py\", line 389, in request\n",
      "    return self.rest_client.GET(url,\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/rest.py\", line 230, in GET\n",
      "    return self.request(\"GET\", url,\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/rest.py\", line 224, in request\n",
      "    raise ApiException(http_resp=r)\n",
      "kfp_server_api.exceptions.ApiException: (503)\n",
      "Reason: Service Unavailable\n",
      "HTTP response headers: HTTPHeaderDict({'content-length': '91', 'content-type': 'text/plain', 'date': 'Sun, 17 Aug 2025 19:22:41 GMT', 'server': 'envoy'})\n",
      "HTTP response body: upstream connect error or disconnect/reset before headers. reset reason: connection timeout\n",
      "\n",
      "ERROR:root:Failed to get healthz info attempt 2 of 5.\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp/client/client.py\", line 424, in get_kfp_healthz\n",
      "    return self._healthz_api.healthz_service_get_healthz()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api/healthz_service_api.py\", line 63, in healthz_service_get_healthz\n",
      "    return self.healthz_service_get_healthz_with_http_info(**kwargs)  # noqa: E501\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api/healthz_service_api.py\", line 134, in healthz_service_get_healthz_with_http_info\n",
      "    return self.api_client.call_api(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py\", line 364, in call_api\n",
      "    return self.__call_api(resource_path, method,\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py\", line 188, in __call_api\n",
      "    raise e\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py\", line 181, in __call_api\n",
      "    response_data = self.request(\n",
      "                    ^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py\", line 389, in request\n",
      "    return self.rest_client.GET(url,\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/rest.py\", line 230, in GET\n",
      "    return self.request(\"GET\", url,\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/rest.py\", line 224, in request\n",
      "    raise ApiException(http_resp=r)\n",
      "kfp_server_api.exceptions.ApiException: (503)\n",
      "Reason: Service Unavailable\n",
      "HTTP response headers: HTTPHeaderDict({'content-length': '91', 'content-type': 'text/plain', 'date': 'Sun, 17 Aug 2025 19:22:56 GMT', 'server': 'envoy'})\n",
      "HTTP response body: upstream connect error or disconnect/reset before headers. reset reason: connection timeout\n",
      "\n",
      "ERROR:root:Failed to get healthz info attempt 3 of 5.\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp/client/client.py\", line 424, in get_kfp_healthz\n",
      "    return self._healthz_api.healthz_service_get_healthz()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api/healthz_service_api.py\", line 63, in healthz_service_get_healthz\n",
      "    return self.healthz_service_get_healthz_with_http_info(**kwargs)  # noqa: E501\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api/healthz_service_api.py\", line 134, in healthz_service_get_healthz_with_http_info\n",
      "    return self.api_client.call_api(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py\", line 364, in call_api\n",
      "    return self.__call_api(resource_path, method,\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py\", line 188, in __call_api\n",
      "    raise e\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py\", line 181, in __call_api\n",
      "    response_data = self.request(\n",
      "                    ^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py\", line 389, in request\n",
      "    return self.rest_client.GET(url,\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/rest.py\", line 230, in GET\n",
      "    return self.request(\"GET\", url,\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/rest.py\", line 224, in request\n",
      "    raise ApiException(http_resp=r)\n",
      "kfp_server_api.exceptions.ApiException: (503)\n",
      "Reason: Service Unavailable\n",
      "HTTP response headers: HTTPHeaderDict({'content-length': '91', 'content-type': 'text/plain', 'date': 'Sun, 17 Aug 2025 19:23:11 GMT', 'server': 'envoy'})\n",
      "HTTP response body: upstream connect error or disconnect/reset before headers. reset reason: connection timeout\n",
      "\n",
      "ERROR:root:Failed to get healthz info attempt 4 of 5.\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp/client/client.py\", line 424, in get_kfp_healthz\n",
      "    return self._healthz_api.healthz_service_get_healthz()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api/healthz_service_api.py\", line 63, in healthz_service_get_healthz\n",
      "    return self.healthz_service_get_healthz_with_http_info(**kwargs)  # noqa: E501\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api/healthz_service_api.py\", line 134, in healthz_service_get_healthz_with_http_info\n",
      "    return self.api_client.call_api(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py\", line 364, in call_api\n",
      "    return self.__call_api(resource_path, method,\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py\", line 188, in __call_api\n",
      "    raise e\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py\", line 181, in __call_api\n",
      "    response_data = self.request(\n",
      "                    ^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py\", line 389, in request\n",
      "    return self.rest_client.GET(url,\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/rest.py\", line 230, in GET\n",
      "    return self.request(\"GET\", url,\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/rest.py\", line 224, in request\n",
      "    raise ApiException(http_resp=r)\n",
      "kfp_server_api.exceptions.ApiException: (503)\n",
      "Reason: Service Unavailable\n",
      "HTTP response headers: HTTPHeaderDict({'content-length': '91', 'content-type': 'text/plain', 'date': 'Sun, 17 Aug 2025 19:23:26 GMT', 'server': 'envoy'})\n",
      "HTTP response body: upstream connect error or disconnect/reset before headers. reset reason: connection timeout\n",
      "\n",
      "ERROR:root:Failed to get healthz info attempt 5 of 5.\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp/client/client.py\", line 424, in get_kfp_healthz\n",
      "    return self._healthz_api.healthz_service_get_healthz()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api/healthz_service_api.py\", line 63, in healthz_service_get_healthz\n",
      "    return self.healthz_service_get_healthz_with_http_info(**kwargs)  # noqa: E501\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api/healthz_service_api.py\", line 134, in healthz_service_get_healthz_with_http_info\n",
      "    return self.api_client.call_api(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py\", line 364, in call_api\n",
      "    return self.__call_api(resource_path, method,\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py\", line 188, in __call_api\n",
      "    raise e\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py\", line 181, in __call_api\n",
      "    response_data = self.request(\n",
      "                    ^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py\", line 389, in request\n",
      "    return self.rest_client.GET(url,\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/rest.py\", line 230, in GET\n",
      "    return self.request(\"GET\", url,\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/kfp_server_api/rest.py\", line 224, in request\n",
      "    raise ApiException(http_resp=r)\n",
      "kfp_server_api.exceptions.ApiException: (503)\n",
      "Reason: Service Unavailable\n",
      "HTTP response headers: HTTPHeaderDict({'content-length': '91', 'content-type': 'text/plain', 'date': 'Sun, 17 Aug 2025 19:23:41 GMT', 'server': 'envoy'})\n",
      "HTTP response body: upstream connect error or disconnect/reset before headers. reset reason: connection timeout\n",
      "\n"
     ]
    },
    {
     "ename": "TimeoutError",
     "evalue": "Failed getting healthz endpoint after 5 attempts.",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTimeoutError\u001b[0m                              Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[1], line 9\u001b[0m\n\u001b[1;32m      6\u001b[0m host_url \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mhttp://istio-ingressgateway.istio-system.svc.cluster.local:8080/pipeline\u001b[39m\u001b[38;5;124m'\u001b[39m\n\u001b[1;32m      8\u001b[0m \u001b[38;5;66;03m# Crea una instancia del cliente de Kubeflow Pipelines especificando el host\u001b[39;00m\n\u001b[0;32m----> 9\u001b[0m client \u001b[38;5;241m=\u001b[39m \u001b[43mClient\u001b[49m\u001b[43m(\u001b[49m\u001b[43mhost\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mhost_url\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/kfp/client/client.py:204\u001b[0m, in \u001b[0;36mClient.__init__\u001b[0;34m(self, host, client_id, namespace, other_client_id, other_client_secret, existing_token, cookies, proxy, ssl_ca_cert, kube_context, credentials, ui_host, verify_ssl)\u001b[0m\n\u001b[1;32m    202\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_upload_api \u001b[38;5;241m=\u001b[39m kfp_server_api\u001b[38;5;241m.\u001b[39mPipelineUploadServiceApi(api_client)\n\u001b[1;32m    203\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_healthz_api \u001b[38;5;241m=\u001b[39m kfp_server_api\u001b[38;5;241m.\u001b[39mHealthzServiceApi(api_client)\n\u001b[0;32m--> 204\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_context_setting[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mnamespace\u001b[39m\u001b[38;5;124m'\u001b[39m] \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget_kfp_healthz\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    205\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;241m.\u001b[39mmulti_user \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mTrue\u001b[39;00m:\n\u001b[1;32m    206\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m    207\u001b[0m         \u001b[38;5;28;01mwith\u001b[39;00m \u001b[38;5;28mopen\u001b[39m(Client\u001b[38;5;241m.\u001b[39m_NAMESPACE_PATH, \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mr\u001b[39m\u001b[38;5;124m'\u001b[39m) \u001b[38;5;28;01mas\u001b[39;00m f:\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/kfp/client/client.py:419\u001b[0m, in \u001b[0;36mClient.get_kfp_healthz\u001b[0;34m(self, sleep_duration)\u001b[0m\n\u001b[1;32m    417\u001b[0m count \u001b[38;5;241m+\u001b[39m\u001b[38;5;241m=\u001b[39m \u001b[38;5;241m1\u001b[39m\n\u001b[1;32m    418\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m count \u001b[38;5;241m>\u001b[39m max_attempts:\n\u001b[0;32m--> 419\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTimeoutError\u001b[39;00m(\n\u001b[1;32m    420\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mFailed getting healthz endpoint after \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mmax_attempts\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m attempts.\u001b[39m\u001b[38;5;124m'\u001b[39m\n\u001b[1;32m    421\u001b[0m     )\n\u001b[1;32m    423\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m    424\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_healthz_api\u001b[38;5;241m.\u001b[39mhealthz_service_get_healthz()\n",
      "\u001b[0;31mTimeoutError\u001b[0m: Failed getting healthz endpoint after 5 attempts."
     ]
    }
   ],
   "source": [
    "import kfp\n",
    "from kfp.client import Client\n",
    "\n",
    "# Reemplaza 'http://<tu-host-de-kubeflow>/pipeline' con la URL real de tu instalación\n",
    "# Por ejemplo: 'http://192.168.1.100/pipeline' o 'https://my-kubeflow-domain.com/pipeline'\n",
    "host_url = 'http://istio-ingressgateway.istio-system.svc.cluster.local:8080/pipeline'\n",
    "\n",
    "# Crea una instancia del cliente de Kubeflow Pipelines especificando el host\n",
    "client = Client(host=host_url)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "828ee2ee-dd10-41b6-afb8-e393eaf12dae",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(503)\n",
      "Reason: Service Unavailable\n",
      "HTTP response headers: HTTPHeaderDict({'content-length': '91', 'content-type': 'text/plain', 'date': 'Sun, 17 Aug 2025 17:17:06 GMT', 'server': 'envoy'})\n",
      "HTTP response body: upstream connect error or disconnect/reset before headers. reset reason: connection timeout\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# Define el nombre del experimento\n",
    "experiment_name = 'mi-primer-experimento'\n",
    "\n",
    "# Crea el experimento si no existe\n",
    "try:\n",
    "    experiment = client.create_experiment(name=experiment_name)\n",
    "    print(f'Experimento \"{experiment_name}\" creado con éxito.')\n",
    "except Exception as e:\n",
    "    print(e)\n",
    "    # print(f'Error al crear el experimento, probablemente ya existe. Usando el experimento existente.')\n",
    "    # experiment = client.get_experiment(experiment_name=experiment_name)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fddd9554-dd5e-476e-a2fd-e72b5725444c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "object_detection",
   "language": "python",
   "name": "env"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
